server:
 port: 8191
spring:
 cloud:
  config:
   server:
    git:
     uri: https://github.com/Hasitha-Su/Rent-a-car-config-store
     default-label: master
     search-paths:
     - 'service-config/*service'
     #username: root
     #passphrase: 12345